# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8c9fc1e75d0574faa07ad56e4d98845fb3c2ddcf668916c9074be4ff2b4b85a1b3c7ea8ce71bd7212799fb037b986f4853710955ebad1fec85932dc77e7b9c8

test:
  secret_key_base: f23ba768ba18ff032aa113e89b5d36e10282a22aefe22c2b6687e68dca6a6836ebc49ee35bfcc3789bc8a334fcc5bacd4567a2dce71607db94ce3823b58a009e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
